import { readFile, writeFile } from "fs/promises";
import path from "path";
const file=path.join(process.cwd(),"data","stock_sector_map.json"),d=JSON.parse(await readFile(file,"utf8"));const P="AI应用",c=(s,...z)=>({primary_sector:P,secondary_sector:s,tertiary_sectors:z});
const rows=[
["300058","蓝色光标",[c("AI内容与营销","AI营销与客服","AIGC图文与视频")],["AI营销","AIGC","智能客服"],"AI营销和AIGC为明确业务布局。"],["300781","因赛集团",[c("AI内容与营销","AI营销与客服","AIGC图文与视频")],["AI营销","AIGC","营销智能体"],"AI营销及营销智能体为主营布局。"],["301171","易点天下",[c("AI内容与营销","AI营销与客服")],["AI营销","智能投放","AIGC相关"],"智能营销和AI投放为明确业务方向。"],["603598","引力传媒",[c("AI内容与营销","AI营销与客服")],["AI营销","AIGC","数字营销"],"数字营销已布局AIGC；该项为相关业务归属。"],
["603039","泛微网络",[c("企业AI软件","AI办公与协同")],["AI办公","协同软件","智能体"],"协同办公产品已集成AI能力。"],["300687","赛意信息",[c("企业AI软件","AI ERP与企业管理"),c("行业AI应用","AI工业与制造")],["企业软件","工业AI","智能制造"],"企业数字化和工业智能应用为主营。"],["300075","数字政通",[c("大模型与智能体","AI智能体"),c("行业AI应用","AI工业与制造")],["城市治理AI","AI智能体","数字政府"],"城市治理智能体和AI应用为明确业务。"],
["688787","海天瑞声",[c("数据与知识服务","数据治理与标注")],["AI数据标注","训练数据","语音数据"],"AI训练数据服务为主营。"],["300166","东方国信",[c("数据与知识服务","数据治理与标注","数据分析与决策智能")],["大数据","数据治理","AI分析"],"大数据和智能分析为主营。"],["300188","美亚柏科",[c("数据与知识服务","数据分析与决策智能")],["数据智能","AI分析","数字取证"],"数据智能分析为主营。"],
["300288","朗玛信息",[c("行业AI应用","AI医疗")],["医疗AI","互联网医疗","医疗数据"],"互联网医疗已布局AI医疗服务。"],["002044","美年健康",[c("行业AI应用","AI医疗")],["健康AI","医疗数据","智能体检"],"健康管理业务引入AI应用；该项为相关业务归属。"],["300803","指南针",[c("行业AI应用","AI金融")],["金融AI","证券软件","智能投顾"],"金融信息服务已布局智能投顾等AI应用。"],["300059","东方财富",[c("行业AI应用","AI金融"),c("数据与知识服务","数据分析与决策智能")],["金融数据","AI投研","智能客服"],"金融数据服务及AI应用为明确业务布局。"],["300451","创业慧康",[c("行业AI应用","AI医疗")],["医疗AI","医疗信息化"],"医疗信息化已布局AI应用。"],["300359","全通教育",[c("行业AI应用","AI教育")],["AI教育","教育信息化"],"教育信息化已布局AI教育。"],
["688686","奥普特",[c("AI视觉与语音","计算机视觉应用")],["机器视觉","视觉AI","工业检测"],"机器视觉主营直接服务AI视觉应用。"],["688003","天准科技",[c("AI视觉与语音","计算机视觉应用"),c("行业AI应用","AI工业与制造")],["机器视觉","工业AI","智能检测"],"机器视觉和工业智能检测为主营。"],["002690","美亚光电",[c("AI视觉与语音","计算机视觉应用")],["智能识别","机器视觉","AI检测"],"智能识别和视觉检测为主营。"],
["300369","绿盟科技",[c("AI安全与可信","AI网络安全","模型安全与治理")],["AI安全","网络安全","大模型安全"],"网络安全业务已布局AI安全。"],["002439","启明星辰",[c("AI安全与可信","AI网络安全","内容安全与审核")],["AI安全","网络安全","内容安全"],"网络安全和内容安全已布局AI能力。"],["300768","迪普科技",[c("AI安全与可信","AI网络安全")],["AI安全","网络安全","智能防护"],"网络安全产品具备智能防护能力。"]
];
const by=new Map(d.stocks.map(x=>[x.code,x]));for(const [code,name,cls,tags,reason] of rows){let s=by.get(code);if(!s){s={code,name,primary_sector:P,classifications:[],product_tags:[],reason};d.stocks.push(s);by.set(code,s)}s.name=name;s.product_tags=[...new Set([...(s.product_tags||[]),...tags])];for(const x of cls){let y=s.classifications.find(q=>(q.primary_sector||s.primary_sector)===P&&q.secondary_sector===x.secondary_sector);if(!y){y={primary_sector:P,secondary_sector:x.secondary_sector,tertiary_sectors:[]};s.classifications.push(y)}y.tertiary_sectors=[...new Set([...y.tertiary_sectors,...x.tertiary_sectors])]}if(!s.reason.includes(reason))s.reason=`${s.reason||''}${s.reason?'；':''}${reason}`};await writeFile(file,`${JSON.stringify(d,null,2)}\n`,"utf8");console.log(`AI应用候选池新增/更新 ${rows.length} 只股票。`);
